### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by malfonso0** [Slava/label-tool#13]
hi.  nice tool.
about the export.. y tryed to open the exported data with labelme or labelimage, and it didnt work.
any other tool that might open this files?
thanks

**Comment by Slava** [comment]
The export was tested with https://github.com/wkentaro/labelme at the time of writing the code (jan 2019). If the format has changed, it is possible the export is no longer compatible. I would welcome contributions to make exporting work nicer with other tools.
