### ISSUE TITLE
Export json files error

### ISSUE THREAD

**Issue by ailias** [Slava/label-tool#5]
Here is the msg:
This site can’t be reachedThe webpage at http://172.27.148.3:3000/api/projects/26/export might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

Actually I have checked two times one by one, so I think maybe we should not cause error when someone was chosen while it was not labeled.

**Comment by JoachimVeulemans** [comment]
@ailias A fix is on the way [here](https://github.com/Slava/label-tool/pull/7) or check out my fork [here](https://github.com/JoachimVeulemans/label-tool).

**Comment by Slava** [comment]
The fix has been merged.
