### ISSUE TITLE
Can you tell me the version of NodeJS used in the project, when I run $yarn install in the server directory it always fails.

### ISSUE THREAD

**Issue by NuaaWill** [Slava/label-tool#57]

**Comment by SRaresP** [comment]
I just managed to get it to _build_ with 15.14.0. Why the H is this not mentioned anywhere is beyond me. Also, you need to install visual studio v140 build tools, here's a link: https://stackoverflow.com/questions/33154696/msbuild-error-the-builds-tools-for-v140-platform-toolset-v140-cannot-be-f

I know this is probably really damn late, but someone may find this useful.

Maintainers, if you care about our sanity, please mention the nodejs version somewhere. Thank you for your work.

**Comment by SRaresP** [comment]
Though, what am I saying, the project is abandoned, but still

**Comment by Slava** [comment]
The node version is pinned in the Dockerfile: https://github.com/Slava/label-tool/blob/master/Dockerfile.
That's the version it was last tested with, but if the dependencies are properly updated, it should continue to work on newer versions of node, too.
